server:
  port: 8080

spring:
  # Carga las variables definidas en el archivo .env
  config:
    import: optional:file:.env[.properties]

  application:
    name: auth-api

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          # Spring Security obtiene las llaves públicas de Cognito
          # para validar la firma de los tokens JWT.
          issuer-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.user-pool-id}

# Configuración de AWS Cognito
aws:
  region: ${AWS_REGION:us-east-1}
  user-pool-id: ${AWS_USER_POOL_ID:TU_USER_POOL_ID}
  client-id: ${AWS_CLIENT_ID:TU_APP_CLIENT_ID}

  # Solo necesario si el App Client tiene Client Secret habilitado
  client-secret: ${AWS_CLIENT_SECRET:}

logging:
  level:
    org.springframework.security: DEBUG
    com.duoc.authapi: DEBUG
